name: Java CI with Gradle and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Setup Forge Workspace
        run: ./gradlew setupCIWorkspace --stacktrace

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fatigue+
          path: ./build/libs/*.jar
